"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](#d9d1af)\
[ 󰕈 ](bg:#d9d1af fg:#090c0c)\
[](bg:#a89b60 fg:#d9d1af)\
$directory\
[](fg:#a89b60 bg:#5a4d2f)\
$git_branch\
$git_status\
[](fg:#5a4d2f bg:#3a3227)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#3a3227 bg:#2a241c)\
$time\
[ ](fg:#2a241c)\
\n$character"""

[directory]
style = "fg:#ffffff bg:#a89b60"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#5a4d2f"
format = '[[ $symbol $branch ](fg:#a89b60 bg:#5a4d2f)]($style)'

[git_status]
style = "bg:#5a4d2f"
format = '[[($all_status$ahead_behind )](fg:#a89b60 bg:#5a4d2f)]($style)'

[nodejs]
symbol = ""
style = "bg:#3a3227"
format = '[[ $symbol ($version) ](fg:#a89b60 bg:#3a3227)]($style)'

[rust]
symbol = ""
style = "bg:#3a3227"
format = '[[ $symbol ($version) ](fg:#a89b60 bg:#3a3227)]($style)'

[golang]
symbol = ""
style = "bg:#3a3227"
format = '[[ $symbol ($version) ](fg:#a89b60 bg:#3a3227)]($style)'

[php]
symbol = ""
style = "bg:#3a3227"
format = '[[ $symbol ($version) ](fg:#a89b60 bg:#3a3227)]($style)'

[time]
disabled = false
time_format = "%T" # Hour:Minute Format
style = "bg:#2a241c"
format = '[[  $time ](fg:#d0c5a0 bg:#2a241c)]($style)'
